version: '3'

services:
  web:
    build: .  
    ports:
      - "8000:80"  
    volumes:
      - .:/var/www/html  
    depends_on:
      - db  

  db:
    image: mysql:5.7 
    environment:
      MYSQL_DATABASE: DrBalcony  
      MYSQL_ROOT_PASSWORD: ""  
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql  
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql 
    command: --default-authentication-plugin=mysql_native_password  
    restart: always  

volumes:
  db_data:  
